# These code should be supported by SAIGE software with two scripts step1_fitNULLGLMM.R and step2_SPAtests.R
# also the codes below should be run in terminal/ server


# random glucose coding
Rscript ./scripts/step1_fitNULLGLMM.R  --useSparseGRMtoFitNULL=FALSE  --plinkFile=./input/missense_dataset  --phenoFile=./input/phenotype.txt  --isCateVarianceRatio=TRUE  --phenoCol=RG_ln  --covarColList=age,sex,PC1,PC2,PC3,PC4,PC5,PC6   --sampleIDColinphenoFile=IID  --traitType=quantitative  --outputPrefix=rg_q_c4  --IsOverwriteVarianceRatioFile=TRUE  --LOCO=FALSE --invNormalize=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/random_glucose/rg_c4.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5   --maxMAF_in_groupTest=0.5  --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=rg_q_c4.rda --varianceRatioFile=rg_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_new.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/random_glucose/rq_c4_group_weighted.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0.5 --minMAC=0 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=rg_q_c4.rda --varianceRatioFile=rg_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_weighted.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/random_glucose/rq_c5_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=rg_q_c3.rda --varianceRatioFile=rg_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c5.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/random_glucose/rg_c6_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=rg_q_c3.rda --varianceRatioFile=rg_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c6.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5,cluster6 --is_fastTest=TRUE
#BMI
Rscript ./scripts/step1_fitNULLGLMM.R  --useSparseGRMtoFitNULL=FALSE  --plinkFile=./input/missense_dataset  --phenoFile=./input/phenotype.txt  --isCateVarianceRatio=TRUE  --phenoCol=BMI_transformed  --covarColList=age,sex,PC1,PC2,PC3,PC4,PC5,PC6   --sampleIDColinphenoFile=IID  --traitType=quantitative  --outputPrefix=bmi_q_c4  --IsOverwriteVarianceRatioFile=TRUE  --LOCO=FALSE --invNormalize=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/BMI/bmi_c4.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --maxMAF_in_groupTest=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=bmi_q_c4.rda --varianceRatioFile=bmi_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_new.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/BMI/bmi_c4_group_weighted.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=bmi_q_c4.rda --varianceRatioFile=bmi_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_weighted.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/BMI/bmi_c5_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=bmi_q_c3.rda --varianceRatioFile=bmi_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c5.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/BMI/bmi_c6_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=bmi_q_c3.rda --varianceRatioFile=bmi_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c6.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5,cluster6 --is_fastTest=TRUE

#LDLC
Rscript ./scripts/step1_fitNULLGLMM.R  --useSparseGRMtoFitNULL=FALSE  --plinkFile=./input/missense_dataset  --phenoFile=./input/phenotype.txt  --isCateVarianceRatio=TRUE  --phenoCol=ldlc_bc  --covarColList=age,sex,PC1,PC2,PC3,PC4,PC5,PC6   --sampleIDColinphenoFile=IID  --traitType=quantitative  --outputPrefix=ldlc_q_c4  --IsOverwriteVarianceRatioFile=TRUE  --LOCO=FALSE --invNormalize=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/ldlc/ldlc_c4.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --maxMAF_in_groupTest=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=ldlc_q_c4.rda --varianceRatioFile=ldlc_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_new.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/ldlc/ldlc_c4_group_weighted.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=ldlc_q_c4.rda --varianceRatioFile=ldlc_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_weighted.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/ldlc/ldlc_c5_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=ldlc_q_c3.rda --varianceRatioFile=ldlc_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c5.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/ldlc/ldlc_c6_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=ldlc_q_c3.rda --varianceRatioFile=ldlc_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c6.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5,cluster6 --is_fastTest=TRUE

#HDLC
Rscript ./scripts/step1_fitNULLGLMM.R  --useSparseGRMtoFitNULL=FALSE  --plinkFile=./input/missense_dataset  --phenoFile=./input/phenotype.txt  --isCateVarianceRatio=TRUE  --phenoCol=hdlc_bc  --covarColList=age,sex,PC1,PC2,PC3,PC4,PC5,PC6   --sampleIDColinphenoFile=IID  --traitType=quantitative  --outputPrefix=hdlc_q_c4  --IsOverwriteVarianceRatioFile=TRUE  --LOCO=FALSE --invNormalize=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/hdlc/hdlc_c4.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --maxMAF_in_groupTest=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=hdlc_q_c4.rda --varianceRatioFile=hdlc_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_new.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/hdlc/hdlc_c4_group_weighted.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=hdlc_q_c4.rda --varianceRatioFile=hdlc_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_weighted.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/hdlc/hdlc_c5_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=hdlc_q_c3.rda --varianceRatioFile=hdlc_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c5.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/hdlc/hdlc_c6_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=hdlc_q_c3.rda --varianceRatioFile=hdlc_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c6.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5,cluster6 --is_fastTest=TRUE


#T2D
Rscript ./scripts/step1_fitNULLGLMM.R  --useSparseGRMtoFitNULL=FALSE  --plinkFile=./input/missense_dataset  --phenoFile=./input/phenotype.txt  --isCateVarianceRatio=TRUE  --phenoCol=T2D  --covarColList=age,sex,PC1,PC2,PC3,PC4,PC5,PC6   --sampleIDColinphenoFile=IID  --traitType=binary  --outputPrefix=t2d_b_c4  --IsOverwriteVarianceRatioFile=TRUE  --LOCO=FALSE --invNormalize=TRUE --cateVarRatioMinMACVecExclude 5,15 --cateVarRatioMaxMACVecInclude 15
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/t2d/t2d_c4.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --maxMAF_in_groupTest=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=t2d_b_c4.rda --varianceRatioFile=t2d_b_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_new.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/t2d/t2d_c4_group_weighted.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=t2d_b_c4.rda --varianceRatioFile=t2d_b_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_weighted.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/t2d/t2d_c5_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=t2d_b_c3.rda --varianceRatioFile=t2d_b_c3.varianceRatio.txt --groupFile=./input/group_snpid_c5.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/t2d/t2d_c6_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=t2d_b_c3.rda --varianceRatioFile=t2d_b_c3.varianceRatio.txt --groupFile=./input/group_snpid_c6.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5,cluster6 --is_fastTest=TRUE

#Trig
Rscript ./scripts/step1_fitNULLGLMM.R  --useSparseGRMtoFitNULL=FALSE  --plinkFile=./input/missense_dataset  --phenoFile=./input/phenotype.txt  --isCateVarianceRatio=TRUE  --phenoCol=triglycerides_bc  --covarColList=age,sex,PC1,PC2,PC3,PC4,PC5,PC6   --sampleIDColinphenoFile=IID  --traitType=quantitative  --outputPrefix=trig_q_c4  --IsOverwriteVarianceRatioFile=TRUE  --LOCO=FALSE --invNormalize=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/triglycerides/trig_c4.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --maxMAF_in_groupTest=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=trig_q_c4.rda --varianceRatioFile=trig_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_new.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/triglycerides/trig_c4_group_weighted.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=trig_q_c4.rda --varianceRatioFile=trig_q_c4.varianceRatio.txt --groupFile=./input/group_snpid_c4_weighted.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/triglycerides/trig_c5_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=trig_q_c3.rda --varianceRatioFile=trig_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c5.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5 --is_fastTest=TRUE
#Rscript ./scripts/step2_SPAtests.R  --bedFile=./input/missense_dataset.bed --bimFile=./input/missense_dataset.bim --famFile=./input/missense_dataset.fam --SAIGEOutputFile=./output/triglycerides/trig_c6_group.txt --chrom=1 --AlleleOrder=ref-first --minMAF=0 --minMAC=0.5 --LOCO=FALSE --sampleFile=./input/samplelist.txt --GMMATmodelFile=trig_q_c3.rda --varianceRatioFile=trig_q_c3.varianceRatio.txt --groupFile=./input/group_snpid_c6.txt --annotation_in_groupTest=cluster1,cluster2,cluster3,cluster4,cluster5,cluster6 --is_fastTest=TRUE

plink --bfile missense_dataset --keep keep_rg.txt --make-bed --out rg_subset
plink --bfile rg_subset --freq --out rg_MAF

plink --bfile missense_dataset --keep keep_t2d.txt --make-bed --out t2d_subset
plink --bfile t2d_subset --freq --out t2d_MAF

plink --bfile missense_dataset --keep keep_ldlc.txt --make-bed --out ldlc_subset
plink --bfile ldlc_subset --freq --out ldlc_MAF

plink --bfile missense_dataset --keep keep_bmi.txt --make-bed --out bmi_subset
plink --bfile bmi_subset --freq --out bmi_MAF
